name: datastore_double_dart_test
description: A simple console application.
version: 0.0.1
#homepage: https://www.example.com
#author: Thanasis Voivodas <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  gcloud: ^0.4.0
  googleapis_auth: ^0.2.3
#dev_dependencies:
#  test: ^0.12.0
